export const GET_PRINTERS_LIST_START = 'GET_PRINTERS_LIST_START';
export const GET_PRINTERS_LIST_ERROR = 'GET_PRINTERS_LIST_ERROR';
export const GET_PRINTERS_LIST_DONE = 'GET_PRINTERS_LIST_DONE';
export const CHANGE_STEP_PRINTER_WIZARD = 'CHANGE_STEP_PRINTER_WIZARD';
