/**
 * PRINTERS
 */
export const GET_PRINTERS_LIST_START = 'GET_PRINTERS_LIST_START';
export const GET_PRINTERS_LIST_ERROR = 'GET_PRINTERS_LIST_ERROR';
export const GET_PRINTERS_LIST_DONE = 'GET_PRINTERS_LIST_DONE';
export const CHANGE_STEP_PRINTER_WIZARD = 'CHANGE_STEP_PRINTER_WIZARD';

/**
 * CATEGORIES
 */

export const CREATE_CATEGORY_START = 'CREATE_CATEGORY_START';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';
export const CREATE_CATEGORY_DONE = 'CREATE_CATEGORY_DONE';
export const GET_CATEGORIES_LIST_START = 'GET_CATEGORIES_LIST_START';
export const GET_CATEGORIES_LIST_ERROR = 'GET_CATEGORIES_LIST_ERROR';
export const GET_CATEGORIES_LIST_DONE = 'GET_CATEGORIES_LIST_DONE';
export const CHANGE_CATEGORY_INPUT = 'CHANGE_CATEGORY_INPUT';
